"""empty message

Revision ID: 24ab98583e99
Revises: df0abbaff52c
Create Date: 2023-09-08 11:27:55.094423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ab98583e99'
down_revision = 'df0abbaff52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_instructors_program_id_programs'), 'programs', ['program_id'], ['id'])
        batch_op.drop_column('teaches')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teaches', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_instructors_program_id_programs'), type_='foreignkey')
        batch_op.drop_column('program_id')

    # ### end Alembic commands ###
