"""empty message

Revision ID: 453856c429fa
Revises: f97d21d842cc
Create Date: 2023-09-18 18:49:58.136242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453856c429fa'
down_revision = 'f97d21d842cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_records_user_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_records_user_id', ['user_id'])

    # ### end Alembic commands ###
