"""empty message

Revision ID: 567eea2a6ad2
Revises: 24ab98583e99
Create Date: 2023-09-09 22:33:19.608139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567eea2a6ad2'
down_revision = '24ab98583e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    # ### end Alembic commands ###
