"""empty message

Revision ID: 695c809262bb
Revises: a7b71a78cf1a
Create Date: 2023-09-19 16:14:50.944001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695c809262bb'
down_revision = 'a7b71a78cf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_instructors_program_id_programs', type_='foreignkey')
        batch_op.drop_column('program_id')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('days', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('days')
        batch_op.drop_column('level')

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_instructors_program_id_programs', 'programs', ['program_id'], ['id'])

    # ### end Alembic commands ###
