"""empty message

Revision ID: 6ea3b057aafe
Revises: 54cb0b18a6fc
Create Date: 2023-09-08 04:09:05.876792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea3b057aafe'
down_revision = '54cb0b18a6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_lb', sa.Integer(), nullable=True))
        batch_op.drop_column('weight')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_ft', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('weight_lb', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weight_lb')
        batch_op.drop_column('height_ft')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), nullable=True))
        batch_op.drop_column('weight_lb')

    # ### end Alembic commands ###
