"""empty message

Revision ID: 7080dc5c25c5
Revises: 9b351488ae1d
Create Date: 2023-09-18 18:27:28.042338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7080dc5c25c5'
down_revision = '9b351488ae1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squats')
    op.drop_table('benches')
    op.drop_table('records')
    with op.batch_alter_table('deadlifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadlifts', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.create_table('records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('weight_lb', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_records_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_records')
    )
    op.create_table('benches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('weight_lb', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_benches_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_benches'),
    sa.UniqueConstraint('user_id', name='uq_benches_user_id')
    )
    op.create_table('squats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('weight_lb', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_squats_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_squats')
    )
    # ### end Alembic commands ###
