"""empty message

Revision ID: 8892cbfbf1a3
Revises: 567eea2a6ad2
Create Date: 2023-09-09 23:19:48.731411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8892cbfbf1a3'
down_revision = '567eea2a6ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_program',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_user_program_program_id_programs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_program_user_id_users'))
    )
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('fk_programs_instructor_id_instructors', type_='foreignkey')
        batch_op.drop_column('instructor_id')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_programs_instructor_id_instructors', 'instructors', ['instructor_id'], ['id'])
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('bio')

    op.drop_table('user_program')
    # ### end Alembic commands ###
