"""empty message

Revision ID: 960f7a0381a9
Revises: 2c7b6fbfd7d3
Create Date: 2023-09-14 02:08:32.262732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960f7a0381a9'
down_revision = '2c7b6fbfd7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
