"""empty message

Revision ID: ab38e9624d43
Revises: bcd332b7012b
Create Date: 2023-09-13 15:14:39.871882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab38e9624d43'
down_revision = 'bcd332b7012b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('weight_lb', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_benches_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benches')),
    sa.UniqueConstraint('user_id', name=op.f('uq_benches_user_id'))
    )
    op.create_table('deadlifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('weight_lb', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_deadlifts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deadlifts')),
    sa.UniqueConstraint('user_id', name=op.f('uq_deadlifts_user_id'))
    )
    op.create_table('squats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('weight_lb', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_squats_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squats'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squats')
    op.drop_table('deadlifts')
    op.drop_table('benches')
    # ### end Alembic commands ###
