"""empty message

Revision ID: de12fd2a2357
Revises: 453856c429fa
Create Date: 2023-09-18 20:01:57.871443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de12fd2a2357'
down_revision = '453856c429fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
