"""empty message

Revision ID: df0abbaff52c
Revises: 6ea3b057aafe
Create Date: 2023-09-08 11:18:20.168842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0abbaff52c'
down_revision = '6ea3b057aafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bmi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmi', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
