"""empty message

Revision ID: e944f9e1f590
Revises: e424b9556f8e
Create Date: 2023-09-21 01:50:51.640829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e944f9e1f590'
down_revision = 'e424b9556f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_weight', sa.Integer(), nullable=False))
        batch_op.alter_column('weight_lb',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('weight_lb',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('body_weight')

    # ### end Alembic commands ###
