"""empty message

Revision ID: f97d21d842cc
Revises: 1fff420e0a3c
Create Date: 2023-09-18 18:47:48.658751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97d21d842cc'
down_revision = '1fff420e0a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('weight_lb', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records')),
    sa.UniqueConstraint('user_id', name=op.f('uq_records_user_id'))
    )
    op.drop_table('deadlifts')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))
        batch_op.drop_column('days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('date')

    op.create_table('deadlifts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('weight_lb', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_deadlifts_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_deadlifts'),
    sa.UniqueConstraint('user_id', name='uq_deadlifts_user_id')
    )
    op.drop_table('records')
    # ### end Alembic commands ###
